/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.document.data.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Document service. Represents a row in the &quot;DocumentData_Document&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.document.data.model.impl.DocumentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.document.data.model.impl.DocumentImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Document
 * @generated
 */
@ProviderType
public interface DocumentModel extends BaseModel<Document> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a document model instance should use the {@link Document} interface instead.
	 */

	/**
	 * Returns the primary key of this document.
	 *
	 * @return the primary key of this document
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this document.
	 *
	 * @param primaryKey the primary key of this document
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the document ID of this document.
	 *
	 * @return the document ID of this document
	 */
	public long getDocumentId();

	/**
	 * Sets the document ID of this document.
	 *
	 * @param documentId the document ID of this document
	 */
	public void setDocumentId(long documentId);

	/**
	 * Returns the tag ID of this document.
	 *
	 * @return the tag ID of this document
	 */
	public long getTagId();

	/**
	 * Sets the tag ID of this document.
	 *
	 * @param tagId the tag ID of this document
	 */
	public void setTagId(long tagId);

	/**
	 * Returns the title of this document.
	 *
	 * @return the title of this document
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this document.
	 *
	 * @param title the title of this document
	 */
	public void setTitle(String title);

	/**
	 * Returns the address of this document.
	 *
	 * @return the address of this document
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this document.
	 *
	 * @param address the address of this document
	 */
	public void setAddress(String address);

	/**
	 * Returns the author of this document.
	 *
	 * @return the author of this document
	 */
	@AutoEscape
	public String getAuthor();

	/**
	 * Sets the author of this document.
	 *
	 * @param author the author of this document
	 */
	public void setAuthor(String author);

	/**
	 * Returns the year published of this document.
	 *
	 * @return the year published of this document
	 */
	public long getYearPublished();

	/**
	 * Sets the year published of this document.
	 *
	 * @param yearPublished the year published of this document
	 */
	public void setYearPublished(long yearPublished);

	/**
	 * Returns the create date of this document.
	 *
	 * @return the create date of this document
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this document.
	 *
	 * @param createDate the create date of this document
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this document.
	 *
	 * @return the modified date of this document
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this document.
	 *
	 * @param modifiedDate the modified date of this document
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public Document cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}