/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.document.data.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Tag service. Represents a row in the &quot;DocumentData_Tag&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.document.data.model.impl.TagModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.document.data.model.impl.TagImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Tag
 * @generated
 */
@ProviderType
public interface TagModel extends BaseModel<Tag> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tag model instance should use the {@link Tag} interface instead.
	 */

	/**
	 * Returns the primary key of this tag.
	 *
	 * @return the primary key of this tag
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tag.
	 *
	 * @param primaryKey the primary key of this tag
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the tag ID of this tag.
	 *
	 * @return the tag ID of this tag
	 */
	public long getTagId();

	/**
	 * Sets the tag ID of this tag.
	 *
	 * @param tagId the tag ID of this tag
	 */
	public void setTagId(long tagId);

	/**
	 * Returns the tag name of this tag.
	 *
	 * @return the tag name of this tag
	 */
	@AutoEscape
	public String getTagName();

	/**
	 * Sets the tag name of this tag.
	 *
	 * @param tagName the tag name of this tag
	 */
	public void setTagName(String tagName);

	/**
	 * Returns the create date of this tag.
	 *
	 * @return the create date of this tag
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this tag.
	 *
	 * @param createDate the create date of this tag
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this tag.
	 *
	 * @return the modified date of this tag
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this tag.
	 *
	 * @param modifiedDate the modified date of this tag
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public Tag cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}